### ISSUE TITLE
Problema na execução do exemplo

### ISSUE THREAD

**Issue by VitorKamida** [paulopinda/nodejs-nbiobsp#1]
Ola,
Estou tendo problema para executar o exemplo, quando eu executo o build-exemplo.sh ele me retornava a uma mensagem falando que não foi possivel encontrar arquivo binding.gyp. Entao eu criei um apenas com target_name.
Com isso ele executou e quando tenta executar o segundo comando que é o nw-gyp build ele retorna: 

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: undefined
gyp ERR! stack     at new SemVer (/usr/local/lib/node_modules/nw-gyp/node_modules/semver/semver.js:279:11)
gyp ERR! stack     at compare (/usr/local/lib/node_modules/nw-gyp/node_modules/semver/semver.js:566:10)
gyp ERR! stack     at Function.gt (/usr/local/lib/node_modules/nw-gyp/node_modules/semver/semver.js:595:10)
gyp ERR! stack     at /usr/local/lib/node_modules/nw-gyp/lib/build.js:67:22
gyp ERR! stack     at /usr/local/lib/node_modules/nw-gyp/node_modules/graceful-fs/graceful-fs.js:78:16
gyp ERR! stack     at fs.js:334:14
gyp ERR! stack     at /usr/local/lib/node_modules/nw-gyp/node_modules/graceful-fs/graceful-fs.js:43:10
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "build"
gyp ERR! cwd /root/biometria/nodejs-nbiobsp/example-webkit
gyp ERR! node -v v0.12.5
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! This is a bug in `nw-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nwjs/nw-gyp/issues>

**Comment by paulo-social** [comment]
Olá, 
Tenta utilizar essa estrutura que está no repositório binding.gyp:

```
{
  "targets": [
    {
      "target_name": "nbiobsp",
      "sources": [ "nbiobsp.cpp" ],
      "libraries": [
        "-lNBioBSP", "-L/lib"
      ],
      "cflags": ["-Wall", "-std=c++11", "-lNBioBSP"],
    }
  ]
}
```
Agora estou sem o equipamento para verificar, se caso ainda não funcionar, tenta executar o exemplo que está no README.md.

**Comment by VitorKamida** [comment]
O exemplo do README funciona, mas quando eu executo o .sh na pasta do exemple-webkit ele retorna esse erro.
A principio tinha dado erro no teste de execução pois ele instalou uma versao do nodejs superior, ai eu fiz a instalação da versao do exemplo manualmente e funcionou, mas quando executei o exemple-webkit deu esse erro.

**Comment by paulo-social** [comment]
Vou tentar conseguir um equipamento para eu poder testar e criar um README.md melhor.
