### ISSUE TITLE
-lNBioBSP

### ISSUE THREAD

**Issue by ezequiel454** [paulopinda/nodejs-nbiobsp#2]
Hi, i got this problem with ever version of node, dont know what to do anymore, drivers it is already installed.
![biopro](https://user-images.githubusercontent.com/11526507/34723614-69a142b0-f532-11e7-82b0-2a24a4ede1ef.png)

**Comment by paulo-social** [comment]
The lib NBioBSP is not found, I sent a e-mail for you.

**Comment by ptcampos** [comment]
Olá Paulo! Obrigado por compartilhar... Estou com o mesmo erro do colega acima. Pode me encaminhar a lib NBioBSP também? Obrigado.

**Comment by ezequiel454** [comment]
o Paulo ficou de atualizar esse modulo.

**Comment by paulo-social** [comment]
@ptcampos está tudo dentro de driver.
@ezequiel454 estou analisando o caso que conversamos, estou tendo problema pra compilar o módulo:

```bash
paulo@paulo-inspiron:~/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit$ sudo ./CreateModule 
[sudo] senha para paulo: 
make -C /lib/modules/4.13.0-38-generic/build SUBDIRS=/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-38-generic'
  CC [M]  /home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o
In file included from /home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:31:0:
./arch/x86/include/asm/uaccess.h: In function ‘set_fs’:
./arch/x86/include/asm/uaccess.h:31:9: error: dereferencing pointer to incomplete type ‘struct task_struct’
  current->thread.addr_limit = fs;
         ^~
/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c: In function ‘hfdu14_read’:
/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:540:24: error: implicit declaration of function ‘copy_to_user’; did you mean ‘raw_copy_to_user’? [-Werror=implicit-function-declaration]
          user_result = copy_to_user(u_buf, dev->bulk_in_buffer, actual_length);
                        ^~~~~~~~~~~~
                        raw_copy_to_user
/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c: In function ‘hfdu14_ioctl’:
/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:1078:27: error: implicit declaration of function ‘copy_from_user’; did you mean ‘raw_copy_from_user’? [-Werror=implicit-function-declaration]
             if ((retval = copy_from_user( sensor_option, (void *) arg, wLength_SET_SENSOR_OPTION )))
                           ^~~~~~~~~~~~~~
                           raw_copy_from_user
cc1: some warnings being treated as errors
make[2]: *** [/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o] Error 1
scripts/Makefile.build:315: recipe for target '/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o' failed
make[1]: *** [_module_/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory] Error 2
Makefile:1550: recipe for target '_module_/home/paulo/projetos/tests/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory' failed
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-38-generic'
make: *** [default] Error 2
Makefile:14: recipe for target 'default' failed
mv: não foi possível obter estado de 'ngstardrv.ko': Arquivo ou diretório não encontrado
Create Module success.
```

**Comment by paulo-social** [comment]
Consegui compilar, essa semana tenho a atualização do módulo, desculpe a demora.

**Comment by paulo-social** [comment]
Também já vou documentar o que precisa mudar no código do driver para poder compilar em kernel acima de 4.12.

**Comment by ezequiel454** [comment]
Opa boa Paulo, to no aguardo :D

2018-04-30 14:35 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by ezequiel454** [comment]
alguma novidade Paulo ?

**Comment by paulo-social** [comment]
Nada ainda, to sem tempo, está complicado, conseguiram resolver o lance do driver? O meu kernel é mais recente, preciso levantar uma VM com a versão do kernel que o driver usa.

**Comment by ezequiel454** [comment]
Aqui não consigo rodar por nada nessa versão antiga do node.

2018-05-17 14:17 GMT-03:00 Paulo Roberto Silva <notifications@github.com>:

**Comment by ezequiel454** [comment]
Mas vc não conseguiu mudar para o node mais recente Paulo ?

**Comment by paulo-social** [comment]
No período que desenvolvi esse, eu utilizava uma versão de kernel inferior, agora pra fazer a atualização, na instalação do driver tive problemas devido a versão do kernel que uso, que é mais nova. Qual versão de kernel que você está usando?

Vai demorar mais que imaginei.

**Comment by Assisneto** [comment]
Alguma novidade?

**Comment by pauloexactaworks** [comment]
Nenhuma, estou sem tempo para mexer, se alguém puder investigar a instalação do driver em versões de kernel mais novos, me ajudaria.

**Comment by pari** [comment]
@paulopinda : I am also waiting for kernel 4.x Support !

**Comment by jeffersonkr** [comment]
> ./CreateModule 
make -C /lib/modules/4.15.0-45-generic/build SUBDIRS=/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-45-generic'
  CC [M]  /home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o
In file included from /home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:31:0:
./arch/x86/include/asm/uaccess.h: In function ‘set_fs’:
./arch/x86/include/asm/uaccess.h:32:9: error: dereferencing pointer to incomplete type ‘struct task_struct’
  current->thread.addr_limit = fs;
         ^~
/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c: In function ‘hfdu14_read’:
/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:540:24: error: implicit declaration of function ‘copy_to_user’; did you mean ‘raw_copy_to_user’? [-Werror=implicit-function-declaration]
          user_result = copy_to_user(u_buf, dev->bulk_in_buffer, actual_length);
                        ^~~~~~~~~~~~
                        raw_copy_to_user
/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c: In function ‘hfdu14_ioctl’:
/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.c:1078:27: error: implicit declaration of function ‘copy_from_user’; did you mean ‘raw_copy_from_user’? [-Werror=implicit-function-declaration]
             if ((retval = copy_from_user( sensor_option, (void *) arg, wLength_SET_SENSOR_OPTION )))
                           ^~~~~~~~~~~~~~
                           raw_copy_from_user
cc1: some warnings being treated as errors
make[2]: *** [/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o] Error 1
scripts/Makefile.build:339: recipe for target '/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory/ngstardrv.o' failed
make[1]: *** [_module_/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory] Error 2
Makefile:1551: recipe for target '_module_/home/jefferson/ProjetosRasp/NBioBSP_Python/python-nbiobsp/utils/hamster-iii/ngstardrv-v1.0.5-2-Ubuntu14.04-64bit/tempDirectory' failed
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-45-generic'
make: *** [default] Error 2
Makefile:14: recipe for target 'default' failed
mv: não foi possível obter estado de 'ngstardrv.ko': Arquivo ou diretório inexistente
Create Module success.


Alguma solução @paulopinda fico no aguardo, obrigado

**Comment by paulo-social** [comment]
Eu não mantenho o driver e sim esse módulo, o suporte do driver para 4.x é com a Nitgen.
