### ISSUE TITLE
Version Problem to build

### ISSUE THREAD

**Issue by ezequiel454** [paulopinda/nodejs-nbiobsp#3]
I got this problem, when i tried to run the test.js.

Node version 9.3

![image](https://user-images.githubusercontent.com/11526507/34994378-7a5119ea-faba-11e7-9f14-96d9206566a8.png)

**Comment by Fuhrmann** [comment]
Yeah, same problem here. Node version 6.13.0

**Comment by Fuhrmann** [comment]
I had to run with sudo to make it work.

**Comment by paulo-social** [comment]
What version of linux?
