### ISSUE TITLE
atualização

### ISSUE THREAD

**Issue by Assisneto** [paulopinda/nodejs-nbiobsp#4]
o drive esta precisando de atualizações? quais?

**Comment by paulo-social** [comment]
Boa pergunta, faz muitos anos que não mexo com ele, se conseguirem achar, mandem uma PR por favor.

**Comment by Assisneto** [comment]
ok, mas você não teria ideia de algo que ficou faltando ou que não tenha ficado legal ou ate mesmo um bug?

**Comment by paulo-social** [comment]
Eu não mantenho o driver, e sim o módulo para nodejs, e o driver é proprietário, não tem muito o que fazer se não cobrar atualização do driver por parte da Nitgen.
